changelog:
  exclude:
    labels:
      - dependencies
      - documentation
      - ignore-for-release
    authors:
      - dependabot

  categories:
    - title: Breaking changes
      labels:
        - breaking

    - title: New commands
      labels:
        - new command

    - title: Other changes
      labels:
        - enhancements
      exclude:
        labels:
          - new command

    - title: Bug fixes
      labels:
        - bug

    - title: Internal changes
      labels:
        - ci
