version: "3"
services:
  ssgbot:
    # image: ghcr.io/obviyus/superseriousbot:latest
    build: .
    volumes:
      - ./db/:/db/
      - ./src:/code/src
      - ./vis/:/code/vis/
    env_file:
      - ssgbot.env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: unless-stopped
    volumes:
      - ./db:/data
