services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --label-enable --cleanup --interval 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ssgbot:
    image: ghcr.io/super-serious/bot:latest
    # build: .
    volumes:
      - /db/:/db/
      - .:/code
    env_file:
      - ssgbot.env
    depends_on:
      - qbt
      - redis
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  redis:
    image: redis:latest
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: unless-stopped
    volumes:
      - /db:/data

  qbt:
    image: ghcr.io/linuxserver/qbittorrent
