[tool.poetry]
name = "SuperSeriousBot"
version = "2.0.0"
description = ""
authors = ["Ayaan Zaidi <hi@obviy.us>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
Cerberus = "^1.3.5"
redis = "^5.0.1"
redvid = "^2.0.2"
python-telegram-bot = { version = "^20.6", extras = [
    "rate-limiter",
    "job-queue",
    "webhooks",
] }
yt-dlp = "^2023.10.7"
asyncpraw = "^7.7.1"
dateparser = "^1.1.8"
coloredlogs = "^15.0.1"
howlongtobeatpy = "^1.0.5"
spurdify = "^0.3.0"
translatepy = "^2.3"
uwuify = "^1.3.0"
geopy = "^2.4.0"
pyvis = "^0.3.2"
networkx = "^3.1"
openai = "^0.28.1"
rotten-tomatoes-client = "^0.0.3"
beautifulsoup4 = "^4.12.2"
simpleaichat = "^0.2.2"
cinemagoer = { git = "https://github.com/cinemagoer/cinemagoer" }
async-lru = "^2.0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
