name: Publish image

on:
  push:
    branches:
      - "master"

jobs:
  publish-docker-image:
    if: github.repository_owner == 'Super-Serious'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the ssgbot Docker image
        run: |
          docker build . --tag ghcr.io/super-serious/bot:latest
          docker push ghcr.io/super-serious/bot:latest
