name: Publish Image

on:
  release:
    types: [ published ]

jobs:
  publish-docker-image:
    if: github.repository_owner == 'Super-Serious'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the SSGBOT Docker image
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build . --tag ghcr.io/super-serious/bot:${TAG} --tag ghcr.io/super-serious/bot:latest
          docker push ghcr.io/super-serious/bot --all-tags
