name: Publish Image

on:
  push:
    branches:
      - "master"

jobs:
  publish-docker-image:
    if: github.repository_owner == 'Super-Serious'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Version
        run: |
          echo "SSGBOT_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.SSGBOT_VERSION }}"
          prerelease: false
          title: "v${{ env.SSGBOT_VERSION }}"
          files: |
            LICENSE

      - name: Build the SSGBOT Docker image
        run: |
          docker build . --tag ghcr.io/super-serious/bot:${SSGBOT_VERSION} --tag ghcr.io/super-serious/bot:latest
          docker push ghcr.io/super-serious/bot --all-tags
