name: Release

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i -g semantic-release @semantic-release/changelog
          semantic-release

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: .
          file: ./Dockerfile
          push: true
          tags: latest
          cache-from: type=gha
          cache-to: type=gha
